name: swa
services:
  postgres:
    image: postgres:15.3-alpine
    environment:
      - POSTGRES_USER=kk-user
      - POSTGRES_PASSWORD=kk-password
      - POSTGRES_DB=keycloak
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    user: '1000'

  keycloak:
    image: bitnami/keycloak:21.1.1
    ports:
      - 8081:8080
    environment:
      - KEYCLOAK_ADMIN_USER=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_DATABASE_VENDOR=postgresql
      - KEYCLOAK_DATABASE_HOST=postgres
      - KEYCLOAK_DATABASE_PORT=5432
      - KEYCLOAK_DATABASE_USER=kk-user
      - KEYCLOAK_DATABASE_PASSWORD=kk-password
      - KEYCLOAK_DATABASE_NAME=keycloak
      - KEYCLOAK_DATABASE_SCHEMA=public
