name: swa
services:
  postgres:
    image: postgres:15.3-alpine
    environment:
      - POSTGRES_USER=kk-user
      - POSTGRES_PASSWORD=kk-password
      - POSTGRES_DB=keycloak
    volumes:
      - postgres-data:/var/lib/postgresql/data

  keycloak:
    image: jboss/keycloak:16.1.1
    ports:
      - 8081:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=postgres
      - DB_ADDR=postgres
      - DB_PORT=5432
      - DB_USER=kk-user
      - DB_PASSWORD=kk-password
      - DB_DATABASE=keycloak
      - DB_SCHEMA=public

volumes:
  postgres-data:
